version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: afm-backend
    restart: unless-stopped
    environment:
      PORT: 3001
      NODE_ENV: production
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    volumes:
      - ./backend/data:/app/data          # JSON data persistence
      - ./backend/backups:/app/backups    # Backup storage
      - ./backend/logs:/app/logs          # Log files
    networks:
      - afm-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: afm-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - afm-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3

# volumes:
  # No database volumes needed - everything is file-based!

networks:
  afm-network:
    driver: bridge 