version: '3.8'

services:
  backend:
    image: blueberryhub92/modelingo:backend-latest
    container_name: afm-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups

  frontend:
    image: blueberryhub92/modelingo:frontend-latest
    container_name: afm-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - backend 